In [7]:
# Gerekli olan kütüpanelerin import edilmesi.

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn import neighbors
# Sklearn kütüpanesinden gerekli model import edilmesi işlemi yapıldı.
from sklearn.svm import SVR

In [6]:
# Bazı algoritmaları çalıştırırken hata olarak görünüyor fakat çalışıyor bu sorunun önüne geçemk için aşağıdaki işlemi gerçekleştiriyorum.

from warnings import filterwarnings
filterwarnings('ignore')

In [5]:
# Veri setinin okunmasını sağlıyorum.
df = pd.read_csv(r"C:\Users\realb\Desktop\ML_dersler\ML_301\Destek Vektör Regresyonu\Hitters.csv")

# Veri setinin içinden eksik gözlemleri çıkarmak gerekiyor bu işlemi yapıyorum.
df = df.dropna()

# Şimdi ise dummies ile kukla veri işlemi yapıyorum. One end coding yöntemi ile bu işlemi yapıyorum.
dms = pd.get_dummies(df[['League', 'Division','NewLeague']])

# Bağımlı değişkenimi "y" atıyorum.
y = df["Salary"]

# Veri setimiz içindeki bağımlı değişkeni ve katogorik değişkenlerin götürülmesi işlemini yapıyorum.
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

# Sonuçunda yukardaki değerlerin dummi versyonlarını ve bağımsız değişkenlerimi bir arada tutma işlemini yapıyorum.
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

# Şimdi ise veri setimizde train ve test ayrımı yapmak için bu ayrımı yapma işlemini yapıyorum.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [9]:
# Burda veri setinde eğer verilerin doğrusal olmadığını düşünürsek burda linear ifadesini değiştirerek başka bir şekilde kulanabiliriz.
svr_model = SVR(kernel="linear").fit(X_train, y_train)

In [10]:
svr_model

SVR(kernel='linear')

In [12]:
dir(svr_model)

['C',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_compute_kernel',
 '_decision_function',
 '_dense_decision_function',
 '_dense_fit',
 '_dense_predict',
 '_dual_coef_',
 '_estimator_type',
 '_gamma',
 '_get_coef',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_impl',
 '_intercept_',
 '_more_tags',
 '_n_support',
 '_num_iter',
 '_parameter_constraints',
 '_probA',
 '_probB',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_'

In [13]:
help(svr_model)

Help on SVR in module sklearn.svm._classes object:

class SVR(sklearn.base.RegressorMixin, sklearn.svm._base.BaseLibSVM)
 |  SVR(*, kernel='rbf', degree=3, gamma='scale', coef0=0.0, tol=0.001, C=1.0, epsilon=0.1, shrinking=True, cache_size=200, verbose=False, max_iter=-1)
 |  
 |  Epsilon-Support Vector Regression.
 |  
 |  The free parameters in the model are C and epsilon.
 |  
 |  The implementation is based on libsvm. The fit time complexity
 |  is more than quadratic with the number of samples which makes it hard
 |  to scale to datasets with more than a couple of 10000 samples. For large
 |  datasets consider using :class:`~sklearn.svm.LinearSVR` or
 |  :class:`~sklearn.linear_model.SGDRegressor` instead, possibly after a
 |  :class:`~sklearn.kernel_approximation.Nystroem` transformer or
 |  other :ref:`kernel_approximation`.
 |  
 |  Read more in the :ref:`User Guide <svm_regression>`.
 |  
 |  Parameters
 |  ----------
 |  kernel : {'linear', 'poly', 'rbf', 'sigmoid', 'precompu

In [14]:
# Şimdi kurulan bu model ile bir tahmin etme işlemi gerçekleştireçeğiz.
svr_model.predict(X_train)[0:10]

array([ 219.32622627,  702.43039317,  623.20559641,  153.77538484,
        463.15191157, 1002.96905384,   55.20051607,  218.47517427,
        466.00937227,  802.1635624 ])

In [15]:
# Burda x test verilerinde bağımsız değişkenleri kulanıp y bağımlı değişkeni tahmin etmeye yönelik bir çalışma yapmaktayım.
svr_model.predict(X_test)[0:10]

array([679.14754919, 633.72883529, 925.68639938, 270.28464317,
       530.26659421, 272.22606175, 549.4423224 , 446.55264396,
       892.8309562 , 677.96856008])

In [16]:
# Ben peki mopdel benklemini çıkarmak istersem bunu nasıl yapmam gerekeçek.
svr_model.intercept_

array([-80.15196063])

In [17]:
# Diğer bütün katsayıları görmnek istersem bunu nasıl yaparım.
svr_model.coef_

array([[ -1.2183904 ,   6.09602978,  -3.67574533,   0.14217072,
          0.51435925,   1.28388992,  12.55922527,  -0.08693754,
          0.46597185,   2.98259931,   0.52944513,  -0.79820793,
         -0.16015531,   0.30872795,   0.28842348,  -1.79560066,
          6.41868986, -10.74313785,   1.33374319]])

In [20]:
# X test veri gurubundaki bağımsız değişkenlerden tahmin yapıp bunun RMSE değerini hesaplamasını yapıyorum.
y_pred = svr_model.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred))

370.0408415795005

Burda kulandığımız kernal dorğural bir kernel eğer isterek doğrusal olmayan bir kernel yapısı ile de çalışma yapabiliriz.

In [22]:
svr_model = SVR(kernel="rbf").fit(X_train, y_train)

In [23]:
y_pred = svr_model.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred))
"""
Bu örnek çok güzel bir örnek lütfen dikatli bakın.
Şimdi burda linear olarak kulandığımızdan daha fazla bir test hatası çıktı buda bu veri gurubunda doğrusal olmayan veri gurubunu kulanılmasının 
hatakı olduğunu ve bu veri gurubundaki verilere liner modelin daha başarılı çalıştığını görüyoruz buda bize şunu göstermekte.
Daha iyi bir model yok farklı durumlarda daha başarılı çaşışan model var.
tabi farklı C değerleri üzerindede değerlendirilmesi gerekir.
"""

460.0032657244849

Model Tuning

In [38]:
svr_model = SVR(kernel = "linear")

In [27]:
help(svr_model)

Help on SVR in module sklearn.svm._classes object:

class SVR(sklearn.base.RegressorMixin, sklearn.svm._base.BaseLibSVM)
 |  SVR(*, kernel='rbf', degree=3, gamma='scale', coef0=0.0, tol=0.001, C=1.0, epsilon=0.1, shrinking=True, cache_size=200, verbose=False, max_iter=-1)
 |  
 |  Epsilon-Support Vector Regression.
 |  
 |  The free parameters in the model are C and epsilon.
 |  
 |  The implementation is based on libsvm. The fit time complexity
 |  is more than quadratic with the number of samples which makes it hard
 |  to scale to datasets with more than a couple of 10000 samples. For large
 |  datasets consider using :class:`~sklearn.svm.LinearSVR` or
 |  :class:`~sklearn.linear_model.SGDRegressor` instead, possibly after a
 |  :class:`~sklearn.kernel_approximation.Nystroem` transformer or
 |  other :ref:`kernel_approximation`.
 |  
 |  Read more in the :ref:`User Guide <svm_regression>`.
 |  
 |  Parameters
 |  ----------
 |  kernel : {'linear', 'poly', 'rbf', 'sigmoid', 'precompu

In [39]:
# Şimdi ben burda yapmak istediğim şu ben burada olası C değerlerini vererek ve bunları k katlı çağraz doğrulama ile işleme alarak olası daha iyi sonuçları ele alıyorum.

# Burda ben C ceza değerlerini paremetre olarak gireçeğim ve bunu olası değerler olarak girilmesini sağlıyorum.
svr_params = {"C": [0.1,0.5,1,3]}

In [40]:
# şimdi bir model nesnesi oluştrup buna paremetre değerleri ve hangi modeli bakladiğini ve cv değerlerini ayarlıyorum.
svr_cv_model = GridSearchCV(svr_model, svr_params, cv = 5).fit(X_train, y_train)

In [42]:
# Ben modelin çalışma sırasındaki adımları raporlamasını istiyorsam bunu bu şakilde yapmalıyım.
svr_cv_model = GridSearchCV(svr_model, svr_params, cv = 5, verbose=2).fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.5; total time=   1.2s
[CV] END ..............................................C=0.5; total time=   0.9s
[CV] END ..............................................C=0.5; total time=   1.1s
[CV] END ..............................................C=0.5; total time=   0.9s
[CV] END ..............................................C=0.5; total time=   1.0s
[CV] END ................................................C=1; total time=   2.5s
[CV] END ........................................

In [43]:
# peki ben burda bilgisayarımdaki işlemci gücünü maksimumda kulanmak istersem nasıl bir işlem yapmalıyım.
svr_cv_model = GridSearchCV(svr_model, svr_params, cv = 5, verbose=2, n_jobs=-1).fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


In [44]:
# Yukardaki model fit etme işleminden sonra ben şimdi burda hangi değerin daha iyi olduğunu burda sorgulamasını yapıyorum.
svr_cv_model.best_params_

{'C': 0.5}

Final modeli

In [49]:
# Final modeli kuruyorum.
svr_tunned = SVR(kernel = "linear", C = 0.5).fit(X_train, y_train)

In [51]:
# Modeli tahmin etirme işlemi gerçekleştiriyorum.
y_pred = svr_tunned.predict(X_test)

In [52]:
# Hata kareler ortalamasını hesaplıyorum "RMSE" değeri.
np.sqrt(mean_squared_error(y_test, y_pred))

367.98747616655294